### ISSUE TITLE
I've added plugin but nothing have changed in my code

### ISSUE THREAD

**Issue by budarin** [vandy/webpack-babel-external-helpers-2#2]
what does it exactly do?
I need to move helpers into common bundle from my async loaded bundles with require.ensure

You write:
A Webpack plugin which automatically configures babel-loader to use external-helpers. And injects babelHelpers object to each bundle specified in the configuration.

But there no any explanation how...
Do I need manually attach babel-helpers script to a page or it plugin do?
I use Webpack 2 & happyPack loader

```
new HappyPack({
            loaders: [{
                path: 'babel-loader',
                query: {
                    babelrc: false,
                    presets: [
                        'react',
                    ],
                    plugins: [
                        'transform-es2015-destructuring',
                        'transform-object-rest-spread',
                        'transform-class-properties',
                        'syntax-trailing-function-commas',
                        'transform-decorators-legacy',
                    ],
                    env: {
                        development: {
                            plugins: [
                                'babel-plugin-transform-react-jsx-self',
                                'babel-plugin-transform-react-jsx-source',
                                ['babel-plugin-runtyper', { enabled: true }],
                            ],
                        },
                        production: {
                            plugins: [
                                'transform-flow-strip-types',
                                'transform-react-remove-prop-types',
                                'transform-react-constant-elements',
                                'transform-react-inline-elements',
                            ],
                        },
                    },
                }
            }],
            tempDir: '.temp/client/happypack',
            threads: 4,
            verbose: false,
            enabled: true,
            cache: true,
            cacheContext: { env: process.env.NODE_ENV },
        }),
```

What should I do to replace such helpers
```
m = function() {
                var s = "function" == typeof Symbol && Symbol.for && Symbol.for("react.element") || 60103;
                return function(u, v, w, x) {
                    var y = u && u.defaultProps, z = arguments.length - 3;
                    if (v || 0 == z || (v = {}), v && y)for (var A in y)void 0 === v[A] && (v[A] = y[A]); else v || (v = y || {});
                    if (1 == z) v.children = x; else if (1 < z) {
                        for (var B = Array(z), C = 0; C < z; C++)B[C] = arguments[C + 3];
                        v.children = B
                    }
                    return { $$typeof: s, type: u, key: void 0 === w ? null : "" + w, ref: null, props: v, _owner: null }
                }
            }()
```
from every module to babelHelpers calls ?
Its unclear should I use babel-plugin-external-helpers or not... so the same question about the helpers...

**Comment by vandy** [comment]
Hello, @budarin. Sorry for late comment, anyway:
If one uses `babel-loader` without `babel-plugin-external-helpers` e.g.
```javascript
// webpack.config.js

module.exports = {
    entry: './main.js',
    module: {
        rules: [{
            test: /\.js$/i,
            loader: 'babel-loader?presets[]=env',
        }],
    }
};
```
Almost every module in the resulting bundle will have lines like this:
```javascript
// ...
var _navigation2 = _interopRequireDefault(_navigation);

// "babel-loader" defines some helper functions inside every module
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
// ...
```

If `babel-loader` is configured to use `babel-plugin-external-helpers` then it doesn't create any helper functions inside modules, it just uses methods of `babelHelpers` object:
```javascript
var _navigation2 = babelHelpers.interopRequireDefault(_navigation);

babelHelpers.classCallCheck(this, SomeClass);
```

So this plugin (`webpack-babel-external-helpers-2`) is very straightforward. At Webpack start after it processed all arguments and loaded configuration files, the plugin processes all Webpack configuration rules in `module.rules` and configures `babel-loader` to use `babel-plugin-external-helpers`:
```javascript
// Webpack configuration

{
    entry: './main.js',
    module: {
        rules: [{
            test: /\.js$/i,
            loader: 'babel-loader?presets[]=env&plugins[]=babel-plugin-external-helpers',
        }],
    }
};
```

Configuring `babel-loader` by itself is not enough though, because if there is no code defining `babelHelpers` object (prior bundle runs) then one gets `ReferenceError` at runtime. This is the second part of the plugin. It injects module to the resulting bundle containing definition of `babelHelpers` object with all its methods or methods specified in `whitelist` option.
```javascript
// resulting bundle

/***/ (function(module, exports) {
(function (global) {
  var babelHelpers = global.babelHelpers = {};
  babelHelpers.typeof = typeof Symbol === "function" &&

// ...

})(typeof global === "undefined" ? self : global);
/***/ }),
```

The same result could be achieved without plugin (`webpack-babel-external-helpers-2`) by creating babel-helpers.js file and using it in webpack configuration:
```cmd
./node_modules/.bin/babel-external-helpers [options] > babel-helpers.js
```
```javascript
// webpack.config.js

module.exports = {
    entry: ['./babel-helpers.js', './main.js'],
    module: {
        rules: [{
            test: /\.js$/i,
            loader: 'babel-loader?presets[]=env&plugins[]=babel-plugin-external-helpers',
        }],
    }
};
```

`HappyPack` is used as a loader in webpack configuration, so there are no other loaders specified in `module.rules`, all loaders are specified inside `HappyPack` options. So `webpack-babel-external-helpers-2` wouldn't work in this case, actually it should throw in strict mode (`strict` option), because it won't find any `babel-loader` in configuration (`module.rules`).

Right now I think this is wontfix. Maybe in future releases there will be another approach concerning such cases as this.

P.S. Helpers example you've posted at the end of your comment seems not to be connected to babelHelpers, so `babel-plugin-external-helpers` can do nothing with this.
